### ISSUE TITLE
Test to do / problems

### ISSUE THREAD

**Issue by mdllz** [ampl-psych/EMC2#62]
- [ ] parallel processing in devtools::check() gives errors
- [ ] github actions does not seem to run the tests
- [ ] expect_doppelganger overwrites svg files on new machine (?)
- [ ] add tests to plots when plot helps are merged
- [x] savage_dickey test gives an error
- [ ] newest mac version does not install emc2
- [ ] saved samplers object for plot function tests is not of class emc
- [ ] tests for S3 functions

**Comment by niekstevenson** [comment]
All fixed!
